import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

const fontFamily = Quicksand({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
    title: "Goldwater Home Loans",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={fontFamily.className}>{children}</body>
        </html>
    );
}